# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_CHARGERPRESENT) 	+= oplus_charger_present.o
obj-$(CONFIG_OPLUS_FEATURE_SIMCARDNUM) 	+= simcardnum.o
